### ISSUE TITLE
Errors building after ReClass.NET update.

### ISSUE THREAD

**Issue by pentoxine** [KN4CK3R/ReClass.NET-FrostbitePlugin#5]

**Comment by pentoxine** [comment]
@KN4CK3R - PR https://github.com/ReClassNET/ReClass.NET-FrostbitePlugin/pull/4 fixes the issue.

**Comment by huangfengye** [comment]
> @KN4CK3R - PR #4 fixes the issue.

hi, bro, test your PR, it not work for last reclass.net tooo....😭
